apiVersion: apps/v1
kind: Deployment
metadata:
  name: hossam-app-deployment
  labels:
    app: hossam-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hossam-app
  template:
    metadata:
      labels:
        app: hossam-app
    spec:
      containers:
      - name: hossam-app-container
        image: hossamcloudscaleregistry.azurecr.io/hossam-app:v1
        ports:
        - containerPort: 5000
        readinessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /health
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 20 
